# Generated by Django 5.0.3 on 2025-04-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_phone_number_order_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
